# sudo docker compose -f docker-compose.vosk.yml up -d

networks:
  infra-network:
    driver: bridge

services:

  # -----------------------------------------
  vosk-server-ru:
    image: alphacep/kaldi-ru:latest
    container_name: vosk-server-ru
    restart: unless-stopped
    ports:
      - "${VOSK_PORT:-7073}:2700"
    networks:
      - infra-network

  # -----------------------------------------
  # Можно и без ffmpeg-api, если планируется работа только с WAV с нужными харакеристиками.
  ffmpeg-api:
    image: msuarezpumpun/ffmpeg-api:latest
    container_name: ffmpeg-api
    restart: unless-stopped
    ports:
      - "${FFMPEG_PORT:-7074}:3000"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    networks:
      - infra-network

  # -----------------------------------------
  vosk-web-api:
    image: vosk.web-api
    container_name: vosk-web-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Vosk.WebApi/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "${WEB_API_PORT:-7075}:8080"
    volumes:
      - "/opt/configs:/opt/configs/:ro"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      FFmpegApiUrl: http://${HOST_IP:-localhost}:${FFMPEG_PORT:-7074}
      VoskWebSocketUrl: ws://${HOST_IP:-localhost}:${VOSK_PORT:-7073}
      ResultChunkSize: 8192
      WavSamplingRateHz: 8000
      WavBitRate: 16
      ForceWavConversion: true
    networks:
      - infra-network
    depends_on:
      - vosk-server-ru