# sudo docker compose -f docker-compose.vosk.yml up -d

name: "vosk-asr"

networks:
  ai-network:
    driver: bridge

services:

  # -----------------------------------------
  vosk-server-ru:
    image: alphacep/kaldi-ru:latest
    container_name: vosk-server-ru
    restart: unless-stopped
    ports:
      - "${VOSK_SERVER_WS_PORT:-2700}:2700"
    networks:
      - ai-network

  # -----------------------------------------
  vosk-web-api:
    image: vosk.web-api
    container_name: vosk-web-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "7075:80"
    volumes:
      - "/opt/configs:/opt/configs/:ro"