# sudo docker compose -f docker-compose.vosk.yml up -d

name: "vosk-asr"

networks:
  vosk-network:
    driver: bridge

services:

  # -----------------------------------------
  vosk-server-ru:
    image: alphacep/kaldi-ru:latest
    container_name: vosk-server-ru
    restart: unless-stopped
    ports:
      - "${VOSK_SERVER_WS_PORT:-2700}:2700"
    networks:
      - vosk-network

  # -----------------------------------------
  audio-converter-web-api:
    image: audio-converter.web-api
    container_name: audio-converter-web-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Vosk.AudioConverter.WebApi/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "${AUDIO_CONVERTER_PORT:-7074}:8080"
    volumes:
      - "/opt/configs:/opt/configs/:ro"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    networks:
      - vosk-network

  # -----------------------------------------
  vosk-web-api:
    image: vosk.web-api
    container_name: vosk-web-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Vosk.WebApi/Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    ports:
      - "${WEB_API_PORT:-7075}:8080"
    volumes:
      - "/opt/configs:/opt/configs/:ro"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
    networks:
      - vosk-network
    depends_on:
      - vosk-server-ru
      - audio-converter-web-api